apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: oracle-connect-cluster
  annotations:
   strimzi.io/use-connector-resources: "true"
spec:
  version: 3.8.0
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: my-cluster-cluster-ca-cert
        pattern: "*.crt"
  config:
    group.id: oracle-connect-cluster
    offset.storage.topic: oracle-connect-cluster-offsets
    config.storage.topic: oracle-connect-cluster-configs
    status.storage.topic: oracle-connect-cluster-status
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  externalConfiguration:
    env:
      - name: ORACLE_USER
        valueFrom:
          secretKeyRef:
            name: oracle-user
            key: username
      - name: ORACLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: oracle-user
            key: password
  build: 
    output: 
      type: imagestream
      image: oracle-streams-connect:latest
    plugins: 
      - name: debezium-connector-oracle
        artifacts:
          - type: zip 
            url: https://maven.repository.redhat.com/ga/io/debezium/debezium-connector-oracle/2.7.3.Final-redhat-00003/debezium-connector-oracle-2.7.3.Final-redhat-00003-plugin.zip
          - type: jar
            url: https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc8/21.6.0.0/ojdbc8-21.6.0.0.jar
