apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: oracle-connect-cluster
  name: <<logical-name>>-connector-oracle 
spec:
  class: io.debezium.connector.oracle.OracleConnector 
  tasksMax: 1  
  config:  
    schema.history.internal.kafka.bootstrap.servers: my-connect-cluster:9092
    schema.history.internal.kafka.topic: schema-changes.<<db name>>
    database.hostname: <<db hostname fqdn>> 
    database.port: 1521   
    database.user: $(env:ORACLE_USER)  
    database.password: ${env:ORACLE_PASSWORD}  
    database.dbname: <<db name>> 
    topic.prefix: <<db name>>-connector-oracle 
    table.include.list: <<schema name>>.<<table name>>
